### Data Manipulation and Analysis using Pandas and Numpy

Data manipulation and analysis are key tasks in any data science or data analysis project. Pandas provides a wide range of functions for data manipulation and analysis, making it easier to clean, transform, and extract insights from data. In this lesson, we will cover various data manipulation and analysis techniques using Python.

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('data.csv')

In [3]:
df.head()

,Unnamed: 0,rank,asin,product_title,product_price,product_star_rating,product_num_ratings,product_url,product_photo,rank_change_label,country,page
0,0,1,B073VKKNN9,Kaspersky | Premium - Total Security (Ultimate...,₹469.00,4.3,13324.0,https://www.amazon.in/dp/B073VKKNN9,https://images-eu.ssl-images-amazon.com/images...,NaN,IN,1
1,1,2,B07PQZJ6Y8,"K7 Security K7, Total Security, 1 User, 1 Year...",₹370.00,4.4,2291.0,https://www.amazon.in/dp/B07PQZJ6Y8,https://images-eu.ssl-images-amazon.com/images...,NaN,IN,1
2,2,3,B0D1KL34JM,Microsoft Office 2021 Professional - Lifetime ...,"₹1,799.00",4.5,388.0,https://www.amazon.in/dp/B0D1KL34JM,https://images-eu.ssl-images-amazon.com/images...,NaN,IN,1
3,3,4,B07B9YYLGG,"Bitdefender - 1 Device,1 Year - Mobile Securit...",₹94.00,4.1,9630.0,https://www.amazon.in/dp/B07B9YYLGG,https://images-eu.ssl-images-amazon.com/images...,NaN,IN,1
4,4,5,B073VLGMZ4,"McAfee Total Protection 2025 | 1 Device, 3 Yea...","₹1,699.00",4.4,5783.0,https://www.amazon.in/dp/B073VLGMZ4,https://images-eu.ssl-images-amazon.com/images...,NaN,IN,1

In [4]:
df.describe()

,Unnamed: 0,rank,product_star_rating,product_num_ratings,rank_change_label,page
count,999.000000,999.000000,969.000000,969.000000,0.0,999.000000
mean,499.000000,50.450450,4.140248,1312.546956,NaN,1.499499
std,288.530761,28.852421,0.496382,3025.241537,NaN,0.500250
min,0.000000,1.000000,1.000000,1.000000,NaN,1.000000
25%,249.500000,25.500000,3.900000,54.000000,NaN,1.000000
50%,499.000000,50.000000,4.200000,218.000000,NaN,1.000000
75%,748.500000,75.000000,4.400000,1009.000000,NaN,2.000000
max,998.000000,100.000000,5.000000,19189.000000,NaN,2.000000

In [5]:
df.drop('rank_change_label', axis=1, inplace=True)

In [8]:
#fetch first 5 rows
df.head(5)

,Unnamed: 0,rank,asin,product_title,product_price,product_star_rating,product_num_ratings,product_url,product_photo,country,page
0,0,1,B073VKKNN9,Kaspersky | Premium - Total Security (Ultimate...,₹469.00,4.3,13324.0,https://www.amazon.in/dp/B073VKKNN9,https://images-eu.ssl-images-amazon.com/images...,IN,1
1,1,2,B07PQZJ6Y8,"K7 Security K7, Total Security, 1 User, 1 Year...",₹370.00,4.4,2291.0,https://www.amazon.in/dp/B07PQZJ6Y8,https://images-eu.ssl-images-amazon.com/images...,IN,1
2,2,3,B0D1KL34JM,Microsoft Office 2021 Professional - Lifetime ...,"₹1,799.00",4.5,388.0,https://www.amazon.in/dp/B0D1KL34JM,https://images-eu.ssl-images-amazon.com/images...,IN,1
3,3,4,B07B9YYLGG,"Bitdefender - 1 Device,1 Year - Mobile Securit...",₹94.00,4.1,9630.0,https://www.amazon.in/dp/B07B9YYLGG,https://images-eu.ssl-images-amazon.com/images...,IN,1
4,4,5,B073VLGMZ4,"McAfee Total Protection 2025 | 1 Device, 3 Yea...","₹1,699.00",4.4,5783.0,https://www.amazon.in/dp/B073VLGMZ4,https://images-eu.ssl-images-amazon.com/images...,IN,1

In [9]:
#fetch last five
df.tail(5)

,Unnamed: 0,rank,asin,product_title,product_price,product_star_rating,product_num_ratings,product_url,product_photo,country,page
994,994,96,B0DP7LBGM1,Microsoft Windows Server 2025 Standard Edition...,"$1,561.01",NaN,NaN,https://www.amazon.com.mx/dp/B0DP7LBGM1,https://images-na.ssl-images-amazon.com/images...,MX,2
995,995,97,B0CFZNMZW6,Photoshop Elements 2024 and Premiere Elements ...,"$3,067.45",4.0,82.0,https://www.amazon.com.mx/dp/B0CFZNMZW6,https://images-na.ssl-images-amazon.com/images...,MX,2
996,996,98,B09H2BRVWZ,Microsoft Office Hogar y Empresa 2021,"$5,999.00",4.9,12.0,https://www.amazon.com.mx/dp/B09H2BRVWZ,https://images-na.ssl-images-amazon.com/images...,MX,2
997,997,99,B0C55NKHKL,"Virtual DJ and Karaoke Studio 8, Lifetime, 1 D...",NaN,3.7,3.0,https://www.amazon.com.mx/dp/B0C55NKHKL,https://images-na.ssl-images-amazon.com/images...,MX,2
998,998,100,B091KJH72X,Corel WordPerfect Office Home & Student 2021 |...,$892.21,4.3,743.0,https://www.amazon.com.mx/dp/B091KJH72X,https://images-na.ssl-images-amazon.com/images...,MX,2

In [11]:
df.describe() #shows the statistical analysis for numerical values only

,Unnamed: 0,rank,product_star_rating,product_num_ratings,page
count,999.000000,999.000000,969.000000,969.000000,999.000000
mean,499.000000,50.450450,4.140248,1312.546956,1.499499
std,288.530761,28.852421,0.496382,3025.241537,0.500250
min,0.000000,1.000000,1.000000,1.000000,1.000000
25%,249.500000,25.500000,3.900000,54.000000,1.000000
50%,499.000000,50.000000,4.200000,218.000000,1.000000
75%,748.500000,75.000000,4.400000,1009.000000,2.000000
max,998.000000,100.000000,5.000000,19189.000000,2.000000

In [14]:
df.dtypes

Unnamed: 0               int64
rank                     int64
asin                    object
product_title           object
product_price           object
product_star_rating    float64
product_num_ratings    float64
product_url             object
product_photo           object
country                 object
page                     int64
dtype: object

In [16]:
#Handling missing values
df.isnull().sum()

Unnamed: 0              0
rank                    0
asin                    0
product_title           0
product_price          54
product_star_rating    30
product_num_ratings    30
product_url             0
product_photo           0
country                 0
page                    0
dtype: int64

In [17]:
df.isnull().any()

Unnamed: 0             False
rank                   False
asin                   False
product_title          False
product_price           True
product_star_rating     True
product_num_ratings     True
product_url            False
product_photo          False
country                False
page                   False
dtype: bool

In [19]:
df_filled = df.fillna(0)

In [20]:
df_filled

,Unnamed: 0,rank,asin,product_title,product_price,product_star_rating,product_num_ratings,product_url,product_photo,country,page
0,0,1,B073VKKNN9,Kaspersky | Premium - Total Security (Ultimate...,₹469.00,4.3,13324.0,https://www.amazon.in/dp/B073VKKNN9,https://images-eu.ssl-images-amazon.com/images...,IN,1
1,1,2,B07PQZJ6Y8,"K7 Security K7, Total Security, 1 User, 1 Year...",₹370.00,4.4,2291.0,https://www.amazon.in/dp/B07PQZJ6Y8,https://images-eu.ssl-images-amazon.com/images...,IN,1
2,2,3,B0D1KL34JM,Microsoft Office 2021 Professional - Lifetime ...,"₹1,799.00",4.5,388.0,https://www.amazon.in/dp/B0D1KL34JM,https://images-eu.ssl-images-amazon.com/images...,IN,1
3,3,4,B07B9YYLGG,"Bitdefender - 1 Device,1 Year - Mobile Securit...",₹94.00,4.1,9630.0,https://www.amazon.in/dp/B07B9YYLGG,https://images-eu.ssl-images-amazon.com/images...,IN,1
4,4,5,B073VLGMZ4,"McAfee Total Protection 2025 | 1 Device, 3 Yea...","₹1,699.00",4.4,5783.0,https://www.amazon.in/dp/B073VLGMZ4,https://images-eu.ssl-images-amazon.com/images...,IN,1
...,...,...,...,...,...,...,...,...,...,...,...
994,994,96,B0DP7LBGM1,Microsoft Windows Server 2025 Standard Edition...,"$1,561.01",0.0,0.0,https://www.amazon.com.mx/dp/B0DP7LBGM1,https://images-na.ssl-images-amazon.com/images...,MX,2
995,995,97,B0CFZNMZW6,Photoshop Elements 2024 and Premiere Elements ...,"$3,067.45",4.0,82.0,https://www.amazon.com.mx/dp/B0CFZNMZW6,https://images-na.ssl-images-amazon.com/images...,MX,2
996,996,98,B09H2BRVWZ,Microsoft Office Hogar y Empresa 2021,"$5,999.00",4.9,12.0,https://www.amazon.com.mx/dp/B09H2BRVWZ,https://images-na.ssl-images-amazon.com/images...,MX,2
997,997,99,B0C55NKHKL,"Virtual DJ and Karaoke Studio 8, Lifetime, 1 D...",0,3.7,3.0,https://www.amazon.com.mx/dp/B0C55NKHKL,https://images-na.ssl-images-amazon.com/images...,MX,2
998,998,100,B091KJH72X,Corel WordPerfect Office Home & Student 2021 |...,$892.21,4.3,743.0,https://www.amazon.com.mx/dp/B091KJH72X,https://images-na.ssl-images-amazon.com/images...,MX,2

In [22]:
#Filling missing values with the mean of the column
df['product_star_rating_filled'] = df['product_star_rating'].fillna(df['product_star_rating'].mean())

In [23]:
df

,Unnamed: 0,rank,asin,product_title,product_price,product_star_rating,product_num_ratings,product_url,product_photo,country,page,product_star_rating_filled
0,0,1,B073VKKNN9,Kaspersky | Premium - Total Security (Ultimate...,₹469.00,4.3,13324.0,https://www.amazon.in/dp/B073VKKNN9,https://images-eu.ssl-images-amazon.com/images...,IN,1,4.300000
1,1,2,B07PQZJ6Y8,"K7 Security K7, Total Security, 1 User, 1 Year...",₹370.00,4.4,2291.0,https://www.amazon.in/dp/B07PQZJ6Y8,https://images-eu.ssl-images-amazon.com/images...,IN,1,4.400000
2,2,3,B0D1KL34JM,Microsoft Office 2021 Professional - Lifetime ...,"₹1,799.00",4.5,388.0,https://www.amazon.in/dp/B0D1KL34JM,https://images-eu.ssl-images-amazon.com/images...,IN,1,4.500000
3,3,4,B07B9YYLGG,"Bitdefender - 1 Device,1 Year - Mobile Securit...",₹94.00,4.1,9630.0,https://www.amazon.in/dp/B07B9YYLGG,https://images-eu.ssl-images-amazon.com/images...,IN,1,4.100000
4,4,5,B073VLGMZ4,"McAfee Total Protection 2025 | 1 Device, 3 Yea...","₹1,699.00",4.4,5783.0,https://www.amazon.in/dp/B073VLGMZ4,https://images-eu.ssl-images-amazon.com/images...,IN,1,4.400000
...,...,...,...,...,...,...,...,...,...,...,...,...
994,994,96,B0DP7LBGM1,Microsoft Windows Server 2025 Standard Edition...,"$1,561.01",NaN,NaN,https://www.amazon.com.mx/dp/B0DP7LBGM1,https://images-na.ssl-images-amazon.com/images...,MX,2,4.140248
995,995,97,B0CFZNMZW6,Photoshop Elements 2024 and Premiere Elements ...,"$3,067.45",4.0,82.0,https://www.amazon.com.mx/dp/B0CFZNMZW6,https://images-na.ssl-images-amazon.com/images...,MX,2,4.000000
996,996,98,B09H2BRVWZ,Microsoft Office Hogar y Empresa 2021,"$5,999.00",4.9,12.0,https://www.amazon.com.mx/dp/B09H2BRVWZ,https://images-na.ssl-images-amazon.com/images...,MX,2,4.900000
997,997,99,B0C55NKHKL,"Virtual DJ and Karaoke Studio 8, Lifetime, 1 D...",NaN,3.7,3.0,https://www.amazon.com.mx/dp/B0C55NKHKL,https://images-na.ssl-images-amazon.com/images...,MX,2,3.700000
998,998,100,B091KJH72X,Corel WordPerfect Office Home & Student 2021 |...,$892.21,4.3,743.0,https://www.amazon.com.mx/dp/B091KJH72X,https://images-na.ssl-images-amazon.com/images...,MX,2,4.300000

In [24]:
df.dtypes

Unnamed: 0                      int64
rank                            int64
asin                           object
product_title                  object
product_price                  object
product_star_rating           float64
product_num_ratings           float64
product_url                    object
product_photo                  object
country                        object
page                            int64
product_star_rating_filled    float64
dtype: object

In [26]:
#Renaming columns
df = df.rename(columns={'product_star_rating':'product_rating'})
df.head()

,Unnamed: 0,rank,asin,product_title,product_price,product_rating,product_num_ratings,product_url,product_photo,country,page,product_star_rating_filled
0,0,1,B073VKKNN9,Kaspersky | Premium - Total Security (Ultimate...,₹469.00,4.3,13324.0,https://www.amazon.in/dp/B073VKKNN9,https://images-eu.ssl-images-amazon.com/images...,IN,1,4.3
1,1,2,B07PQZJ6Y8,"K7 Security K7, Total Security, 1 User, 1 Year...",₹370.00,4.4,2291.0,https://www.amazon.in/dp/B07PQZJ6Y8,https://images-eu.ssl-images-amazon.com/images...,IN,1,4.4
2,2,3,B0D1KL34JM,Microsoft Office 2021 Professional - Lifetime ...,"₹1,799.00",4.5,388.0,https://www.amazon.in/dp/B0D1KL34JM,https://images-eu.ssl-images-amazon.com/images...,IN,1,4.5
3,3,4,B07B9YYLGG,"Bitdefender - 1 Device,1 Year - Mobile Securit...",₹94.00,4.1,9630.0,https://www.amazon.in/dp/B07B9YYLGG,https://images-eu.ssl-images-amazon.com/images...,IN,1,4.1
4,4,5,B073VLGMZ4,"McAfee Total Protection 2025 | 1 Device, 3 Yea...","₹1,699.00",4.4,5783.0,https://www.amazon.in/dp/B073VLGMZ4,https://images-eu.ssl-images-amazon.com/images...,IN,1,4.4

In [31]:
#Change datatypes
df['product_rating_new'] = df['product_rating'].fillna(df['product_rating'].mean()).astype(int)
df

,Unnamed: 0,rank,asin,product_title,product_price,product_rating,product_num_ratings,product_url,product_photo,country,page,product_star_rating_filled,rank_new,product_rating_new
0,0,1,B073VKKNN9,Kaspersky | Premium - Total Security (Ultimate...,₹469.00,4.3,13324.0,https://www.amazon.in/dp/B073VKKNN9,https://images-eu.ssl-images-amazon.com/images...,IN,1,4.300000,1,4
1,1,2,B07PQZJ6Y8,"K7 Security K7, Total Security, 1 User, 1 Year...",₹370.00,4.4,2291.0,https://www.amazon.in/dp/B07PQZJ6Y8,https://images-eu.ssl-images-amazon.com/images...,IN,1,4.400000,2,4
2,2,3,B0D1KL34JM,Microsoft Office 2021 Professional - Lifetime ...,"₹1,799.00",4.5,388.0,https://www.amazon.in/dp/B0D1KL34JM,https://images-eu.ssl-images-amazon.com/images...,IN,1,4.500000,3,4
3,3,4,B07B9YYLGG,"Bitdefender - 1 Device,1 Year - Mobile Securit...",₹94.00,4.1,9630.0,https://www.amazon.in/dp/B07B9YYLGG,https://images-eu.ssl-images-amazon.com/images...,IN,1,4.100000,4,4
4,4,5,B073VLGMZ4,"McAfee Total Protection 2025 | 1 Device, 3 Yea...","₹1,699.00",4.4,5783.0,https://www.amazon.in/dp/B073VLGMZ4,https://images-eu.ssl-images-amazon.com/images...,IN,1,4.400000,5,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
994,994,96,B0DP7LBGM1,Microsoft Windows Server 2025 Standard Edition...,"$1,561.01",NaN,NaN,https://www.amazon.com.mx/dp/B0DP7LBGM1,https://images-na.ssl-images-amazon.com/images...,MX,2,4.140248,96,4
995,995,97,B0CFZNMZW6,Photoshop Elements 2024 and Premiere Elements ...,"$3,067.45",4.0,82.0,https://www.amazon.com.mx/dp/B0CFZNMZW6,https://images-na.ssl-images-amazon.com/images...,MX,2,4.000000,97,4
996,996,98,B09H2BRVWZ,Microsoft Office Hogar y Empresa 2021,"$5,999.00",4.9,12.0,https://www.amazon.com.mx/dp/B09H2BRVWZ,https://images-na.ssl-images-amazon.com/images...,MX,2,4.900000,98,4
997,997,99,B0C55NKHKL,"Virtual DJ and Karaoke Studio 8, Lifetime, 1 D...",NaN,3.7,3.0,https://www.amazon.com.mx/dp/B0C55NKHKL,https://images-na.ssl-images-amazon.com/images...,MX,2,3.700000,99,3
998,998,100,B091KJH72X,Corel WordPerfect Office Home & Student 2021 |...,$892.21,4.3,743.0,https://www.amazon.com.mx/dp/B091KJH72X,https://images-na.ssl-images-amazon.com/images...,MX,2,4.300000,100,4

In [32]:
df['Rating_Lambda'] = df['product_rating_new'].apply(lambda x: x**2)
df

,Unnamed: 0,rank,asin,product_title,product_price,product_rating,product_num_ratings,product_url,product_photo,country,page,product_star_rating_filled,rank_new,product_rating_new,Rating_Lambda
0,0,1,B073VKKNN9,Kaspersky | Premium - Total Security (Ultimate...,₹469.00,4.3,13324.0,https://www.amazon.in/dp/B073VKKNN9,https://images-eu.ssl-images-amazon.com/images...,IN,1,4.300000,1,4,16
1,1,2,B07PQZJ6Y8,"K7 Security K7, Total Security, 1 User, 1 Year...",₹370.00,4.4,2291.0,https://www.amazon.in/dp/B07PQZJ6Y8,https://images-eu.ssl-images-amazon.com/images...,IN,1,4.400000,2,4,16
2,2,3,B0D1KL34JM,Microsoft Office 2021 Professional - Lifetime ...,"₹1,799.00",4.5,388.0,https://www.amazon.in/dp/B0D1KL34JM,https://images-eu.ssl-images-amazon.com/images...,IN,1,4.500000,3,4,16
3,3,4,B07B9YYLGG,"Bitdefender - 1 Device,1 Year - Mobile Securit...",₹94.00,4.1,9630.0,https://www.amazon.in/dp/B07B9YYLGG,https://images-eu.ssl-images-amazon.com/images...,IN,1,4.100000,4,4,16
4,4,5,B073VLGMZ4,"McAfee Total Protection 2025 | 1 Device, 3 Yea...","₹1,699.00",4.4,5783.0,https://www.amazon.in/dp/B073VLGMZ4,https://images-eu.ssl-images-amazon.com/images...,IN,1,4.400000,5,4,16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
994,994,96,B0DP7LBGM1,Microsoft Windows Server 2025 Standard Edition...,"$1,561.01",NaN,NaN,https://www.amazon.com.mx/dp/B0DP7LBGM1,https://images-na.ssl-images-amazon.com/images...,MX,2,4.140248,96,4,16
995,995,97,B0CFZNMZW6,Photoshop Elements 2024 and Premiere Elements ...,"$3,067.45",4.0,82.0,https://www.amazon.com.mx/dp/B0CFZNMZW6,https://images-na.ssl-images-amazon.com/images...,MX,2,4.000000,97,4,16
996,996,98,B09H2BRVWZ,Microsoft Office Hogar y Empresa 2021,"$5,999.00",4.9,12.0,https://www.amazon.com.mx/dp/B09H2BRVWZ,https://images-na.ssl-images-amazon.com/images...,MX,2,4.900000,98,4,16
997,997,99,B0C55NKHKL,"Virtual DJ and Karaoke Studio 8, Lifetime, 1 D...",NaN,3.7,3.0,https://www.amazon.com.mx/dp/B0C55NKHKL,https://images-na.ssl-images-amazon.com/images...,MX,2,3.700000,99,3,9
998,998,100,B091KJH72X,Corel WordPerfect Office Home & Student 2021 |...,$892.21,4.3,743.0,https://www.amazon.com.mx/dp/B091KJH72X,https://images-na.ssl-images-amazon.com/images...,MX,2,4.300000,100,4,16

### Data aggregating and grouping

In [33]:
df.head()

,Unnamed: 0,rank,asin,product_title,product_price,product_rating,product_num_ratings,product_url,product_photo,country,page,product_star_rating_filled,rank_new,product_rating_new,Rating_Lambda
0,0,1,B073VKKNN9,Kaspersky | Premium - Total Security (Ultimate...,₹469.00,4.3,13324.0,https://www.amazon.in/dp/B073VKKNN9,https://images-eu.ssl-images-amazon.com/images...,IN,1,4.3,1,4,16
1,1,2,B07PQZJ6Y8,"K7 Security K7, Total Security, 1 User, 1 Year...",₹370.00,4.4,2291.0,https://www.amazon.in/dp/B07PQZJ6Y8,https://images-eu.ssl-images-amazon.com/images...,IN,1,4.4,2,4,16
2,2,3,B0D1KL34JM,Microsoft Office 2021 Professional - Lifetime ...,"₹1,799.00",4.5,388.0,https://www.amazon.in/dp/B0D1KL34JM,https://images-eu.ssl-images-amazon.com/images...,IN,1,4.5,3,4,16
3,3,4,B07B9YYLGG,"Bitdefender - 1 Device,1 Year - Mobile Securit...",₹94.00,4.1,9630.0,https://www.amazon.in/dp/B07B9YYLGG,https://images-eu.ssl-images-amazon.com/images...,IN,1,4.1,4,4,16
4,4,5,B073VLGMZ4,"McAfee Total Protection 2025 | 1 Device, 3 Yea...","₹1,699.00",4.4,5783.0,https://www.amazon.in/dp/B073VLGMZ4,https://images-eu.ssl-images-amazon.com/images...,IN,1,4.4,5,4,16

In [35]:
grouped_mean = df.groupby('product_rating_new')['Rating_Lambda'].mean()

In [36]:
grouped_mean

product_rating_new
1     1.0
2     4.0
3     9.0
4    16.0
5    25.0
Name: Rating_Lambda, dtype: float64

In [37]:
df = pd.read_csv('sample_data.csv')

In [38]:
df

          Date     Category  Value   Product  Sales Region
0   2023-03-18         Food  474.0  Product1  323.0   East
1   2023-12-02         Food  607.0  Product2  324.0    NaN
2   2023-11-06     Clothing  342.0  Product2  310.0   West
3   2023-10-19     Clothing  804.0  Product2  175.0   East
4   2023-04-22    Furniture  129.0  Product2  479.0   East
5   2023-05-10    Furniture  463.0  Product1  335.0   West
6   2023-07-15         Food  644.0  Product1  246.0  South
7   2023-02-04          NaN  795.0  Product1  481.0   West
8   2023-07-20     Clothing  483.0  Product2  387.0   West
9   2023-12-18     Clothing  513.0  Product3  411.0  North
10  2023-12-14          NaN  118.0  Product2  394.0   East
11  2023-04-17     Clothing  253.0  Product2  383.0    NaN
12  2023-06-03     Clothing  504.0  Product2   17.0  North
13  2023-06-29          NaN  282.0  Product2  198.0  South
14  2023-05-02  Electronics  388.0  Product3  352.0   West
15  2023-11-22         Food  508.0  Product3  299.0  North
16  2023-09-17    Furniture  586.0  Product2   17.0   East
17  2023-02-07    Furniture  358.0  Product3  420.0   East
18  2023-06-04  Electronics  860.0  Product2    NaN   East
19  2023-01-22          NaN  247.0  Product2   26.0  North
20  2023-07-11         Food  546.0  Product1  155.0   East
21  2023-06-18    Furniture  127.0  Product3  493.0   East
22  2023-09-13         Food  642.0  Product1  235.0    NaN
23  2023-12-09    Furniture  552.0  Product2  147.0  South
24  2023-10-31         Food  874.0  Product1  298.0  South
25  2023-05-12     Clothing  165.0  Product1  225.0   West
26  2023-03-17    Furniture  324.0  Product1  483.0   East
27  2023-12-07  Electronics  761.0  Product1  126.0   East
28  2023-06-28         Food  142.0  Product3  391.0  South
29  2023-02-09     Clothing  352.0  Product3  188.0   East
30  2023-06-06     Clothing  813.0  Product2  145.0  South
31  2023-06-26         Food  146.0  Product2    NaN   West
32  2023-01-09     Clothing  111.0  Product1  305.0  South
33  2023-11-26    Furniture  851.0  Product3  129.0   East
34  2023-07-06     Clothing  188.0  Product3  415.0   West
35  2023-05-18         Food  459.0  Product3  201.0   East
36  2023-12-21         Food  864.0  Product1  496.0  North
37  2023-08-22     Clothing  619.0  Product1  185.0  South
38  2023-05-11     Clothing  911.0  Product2   89.0   East
39  2023-12-24         Food  560.0  Product3  157.0   West
40  2023-04-24  Electronics  185.0  Product1    NaN  North
41  2023-03-25    Furniture  497.0  Product3  419.0  North
42  2023-09-18          NaN    NaN  Product2   70.0   West
43  2023-01-06         Food    NaN  Product2  109.0   East
44  2023-08-09          NaN  673.0  Product3  457.0  South
45  2023-09-02         Food  656.0  Product3  100.0  North
46  2023-12-05  Electronics    NaN  Product2  309.0  North
47  2023-04-19          NaN  876.0  Product3    NaN  South
48  2023-09-04     Clothing  129.0  Product3  464.0   East
49  2023-06-18    Furniture  743.0  Product2  186.0  South

In [39]:
df.isnull().any()

Date        False
Category     True
Value        True
Product     False
Sales        True
Region       True
dtype: bool

In [40]:
df['Value_Filled'] = df['Value'].fillna(df['Value'].mean())

In [42]:
df

          Date     Category  Value   Product  Sales Region  Value_Filled
0   2023-03-18         Food  474.0  Product1  323.0   East         474.0
1   2023-12-02         Food  607.0  Product2  324.0    NaN         607.0
2   2023-11-06     Clothing  342.0  Product2  310.0   West         342.0
3   2023-10-19     Clothing  804.0  Product2  175.0   East         804.0
4   2023-04-22    Furniture  129.0  Product2  479.0   East         129.0
5   2023-05-10    Furniture  463.0  Product1  335.0   West         463.0
6   2023-07-15         Food  644.0  Product1  246.0  South         644.0
7   2023-02-04          NaN  795.0  Product1  481.0   West         795.0
8   2023-07-20     Clothing  483.0  Product2  387.0   West         483.0
9   2023-12-18     Clothing  513.0  Product3  411.0  North         513.0
10  2023-12-14          NaN  118.0  Product2  394.0   East         118.0
11  2023-04-17     Clothing  253.0  Product2  383.0    NaN         253.0
12  2023-06-03     Clothing  504.0  Product2   17.0  North         504.0
13  2023-06-29          NaN  282.0  Product2  198.0  South         282.0
14  2023-05-02  Electronics  388.0  Product3  352.0   West         388.0
15  2023-11-22         Food  508.0  Product3  299.0  North         508.0
16  2023-09-17    Furniture  586.0  Product2   17.0   East         586.0
17  2023-02-07    Furniture  358.0  Product3  420.0   East         358.0
18  2023-06-04  Electronics  860.0  Product2    NaN   East         860.0
19  2023-01-22          NaN  247.0  Product2   26.0  North         247.0
20  2023-07-11         Food  546.0  Product1  155.0   East         546.0
21  2023-06-18    Furniture  127.0  Product3  493.0   East         127.0
22  2023-09-13         Food  642.0  Product1  235.0    NaN         642.0
23  2023-12-09    Furniture  552.0  Product2  147.0  South         552.0
24  2023-10-31         Food  874.0  Product1  298.0  South         874.0
25  2023-05-12     Clothing  165.0  Product1  225.0   West         165.0
26  2023-03-17    Furniture  324.0  Product1  483.0   East         324.0
27  2023-12-07  Electronics  761.0  Product1  126.0   East         761.0
28  2023-06-28         Food  142.0  Product3  391.0  South         142.0
29  2023-02-09     Clothing  352.0  Product3  188.0   East         352.0
30  2023-06-06     Clothing  813.0  Product2  145.0  South         813.0
31  2023-06-26         Food  146.0  Product2    NaN   West         146.0
32  2023-01-09     Clothing  111.0  Product1  305.0  South         111.0
33  2023-11-26    Furniture  851.0  Product3  129.0   East         851.0
34  2023-07-06     Clothing  188.0  Product3  415.0   West         188.0
35  2023-05-18         Food  459.0  Product3  201.0   East         459.0
36  2023-12-21         Food  864.0  Product1  496.0  North         864.0
37  2023-08-22     Clothing  619.0  Product1  185.0  South         619.0
38  2023-05-11     Clothing  911.0  Product2   89.0   East         911.0
39  2023-12-24         Food  560.0  Product3  157.0   West         560.0
40  2023-04-24  Electronics  185.0  Product1    NaN  North         185.0
41  2023-03-25    Furniture  497.0  Product3  419.0  North         497.0
42  2023-09-18          NaN    NaN  Product2   70.0   West         492.0
43  2023-01-06         Food    NaN  Product2  109.0   East         492.0
44  2023-08-09          NaN  673.0  Product3  457.0  South         673.0
45  2023-09-02         Food  656.0  Product3  100.0  North         656.0
46  2023-12-05  Electronics    NaN  Product2  309.0  North         492.0
47  2023-04-19          NaN  876.0  Product3    NaN  South         876.0
48  2023-09-04     Clothing  129.0  Product3  464.0   East         129.0
49  2023-06-18    Furniture  743.0  Product2  186.0  South         743.0

In [43]:
df.dtypes

Date             object
Category         object
Value           float64
Product          object
Sales           float64
Region           object
Value_Filled    float64
dtype: object

In [44]:
grouped_mean = df.groupby('Product')['Value_Filled'].mean()

In [45]:
grouped_mean

Product
Product1    533.357143
Product2    492.800000
Product3    454.812500
Name: Value_Filled, dtype: float64

In [46]:
grouped_sum = df.groupby(['Product','Region'])['Value_Filled'].sum()
grouped_sum

Product   Region
Product1  East      2105.0
          North     1049.0
          South     2248.0
          West      1423.0
Product2  East      3900.0
          North     1243.0
          South     2390.0
          West      1463.0
Product3  East      2276.0
          North     2174.0
          South     1691.0
          West      1136.0
Name: Value_Filled, dtype: float64

In [56]:
#aggregate multiple functions
df['Value'].fillna(df['Value'].mean())
grouped_agg = df.groupby('Region')['Value'].agg(['mean','sum','count'])

In [57]:
grouped_agg

              mean     sum  count
Region
East    487.117647  8281.0     17
North   496.222222  4466.0      9
South   575.363636  6329.0     11
West    402.200000  4022.0     10

In [58]:
##merging and joining dataframes
#Create sample DataFrames
df1 = pd.DataFrame({'Key':['A','B','C'], 'Value1':[1,2,3]})
df2 = pd.DataFrame({'Key':['A','B','D'], 'Value1':[4,5,6]})

In [59]:
df1

  Key  Value1
0   A       1
1   B       2
2   C       3

In [60]:
df2

  Key  Value1
0   A       4
1   B       5
2   D       6

In [66]:
#Merge Dataframes on the "Key" columns
pd.merge(df1, df2, on='Key', how='inner')

  Key  Value1_x  Value1_y
0   A         1         4
1   B         2         5

In [68]:
pd.merge(df1, df2, on='Key', how='outer')

  Key  Value1_x  Value1_y
0   A       1.0       4.0
1   B       2.0       5.0
2   C       3.0       NaN
3   D       NaN       6.0